# Generated by Django 5.0.6 on 2025-01-23 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkingDrawings', '0002_electricalfixtures_delete_project'),
        ('project', '0003_basefilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDrawingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_type', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('structural', 'Structural')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subproject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_drawing', to='project.subproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
