# Generated by Django 5.0.6 on 2025-01-24 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkingDrawings', '0003_workingdrawingproject'),
        ('project', '0003_basefilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalWiring',
            fields=[
                ('basefilemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.basefilemodel')),
                ('input_file', models.FileField(upload_to='electrical/wiring/inputs/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='electrical/wiring/outputs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_wiring', to='project.subproject')),
            ],
            bases=('project.basefilemodel',),
        ),
    ]
