# Generated by Django 5.0.6 on 2025-01-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkingDrawings', '0004_electricalwiring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingdrawingproject',
            options={},
        ),
        migrations.RemoveField(
            model_name='workingdrawingproject',
            name='drawing_type',
        ),
    ]
