# Generated by Django 5.0.6 on 2025-01-27 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkingDrawings', '0006_watersupply'),
        ('project', '0003_basefilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlumbingComplete',
            fields=[
                ('basefilemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.basefilemodel')),
                ('input_file', models.FileField(upload_to='plumbing/complete/inputs/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='plumbing/complete/outputs/')),
                ('input1_option', models.CharField(default='yes', max_length=3)),
                ('input2_option', models.CharField(default='yes', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plumbing_complete', to='project.subproject')),
            ],
            bases=('project.basefilemodel',),
        ),
    ]
