# Generated by Django 5.0.6 on 2025-02-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkingDrawings', '0007_plumbingcomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='plumbingcomplete',
            name='boq_output_file',
            field=models.FileField(blank=True, null=True, upload_to='plumbing/complete/boq/'),
        ),
    ]
