# Generated by Django 5.0.6 on 2024-12-27 10:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlanning', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorplanningProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('car', models.IntegerField()),
                ('temple', models.IntegerField()),
                ('garden', models.IntegerField()),
                ('living_room', models.IntegerField()),
                ('store_room', models.IntegerField()),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorplanning', to='project.subproject')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='mapfile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='user',
        ),
        migrations.AddField(
            model_name='mapfile',
            name='floorplanning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_files', to='FloorPlanning.floorplanningproject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soildata',
            name='floorplanning',
            field=models.ForeignKey(default=234, on_delete=django.db.models.deletion.CASCADE, related_name='soil_data', to='FloorPlanning.floorplanningproject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfile',
            name='floorplanning',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_files', to='FloorPlanning.floorplanningproject'),
            preserve_default=False,
        ),
    ]
