# Generated by Django 5.0.6 on 2025-01-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlanning', '0003_userfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='size',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
