# Generated by Django 5.0.6 on 2025-01-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FloorPlanning', '0004_userfile_size'),
        ('project', '0003_basefilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='size',
        ),
        migrations.RemoveField(
            model_name='userfile',
            name='user',
        ),
        migrations.AddField(
            model_name='userfile',
            name='basefilemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.basefilemodel'),
            preserve_default=False,
        ),
    ]
