# Generated by Django 5.0.6 on 2025-01-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='project_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='used_storage_gb',
            field=models.FloatField(default=0.0),
        ),
    ]
