# Generated by Django 5.0.6 on 2025-01-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0002_customerprofile_project_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='has_free_project',
            field=models.BooleanField(default=False),
        ),
    ]
