# Generated by Django 5.0.6 on 2024-11-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='project',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='threedmodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='threedmodel',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='workingdrawing',
            name='project',
        ),
        migrations.RemoveField(
            model_name='workingdrawing',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='project',
            name='input_file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='output_file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Concept',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='ThreeDModel',
        ),
        migrations.DeleteModel(
            name='WorkingDrawing',
        ),
    ]
