# Generated by Django 5.0.6 on 2025-01-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
