# Generated by Django 5.0.6 on 2024-11-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_plan_project_remove_plan_uploaded_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='project',
            name='electrical',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='plumbing',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='structural',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
    ]
