# Generated by Django 5.0.6 on 2024-08-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0004_remove_mapfile_map_html_mapfile_map_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='dxf_file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='png_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
