# Generated by Django 5.0.6 on 2024-08-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0005_alter_userfile_dxf_file_alter_userfile_png_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='dxf_file',
            field=models.FileField(blank=True, null=True, upload_to='dxfs/'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='png_image',
            field=models.ImageField(blank=True, null=True, upload_to='pngs/'),
        ),
    ]
